name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test on Ruby ${{ matrix.ruby_version }}, Rails ${{ matrix.rails_version }}, graphql-ruby ${{ matrix.graphql_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.5
          - 2.6
        graphql_version:
          - 1.10.14
          - 1.11.1
          - 2.0.0
        rails_version:
          - "~> 5.2.0"
          - "~> 6.0.0"
        include:
          - ruby_version: 3.0
            graphql_version: 2.0.0
            rails_version: "~> 7.0.0"
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      GRAPHQL_VERSION: ${{ matrix.graphql_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
        rubygems: latest
    - name: Build and test
      run: bundle exec rake test

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Lint
      run: bundle exec rake rubocop
